Update SAST_PR_Scanning.yml

diff --git a/.github/workflows/SAST_PR_Scanning.yml b/.github/workflows/SAST_PR_Scanning.yml
--- a/.github/workflows/SAST_PR_Scanning.yml
+++ b/.github/workflows/SAST_PR_Scanning.yml
@@ -1,20 +1,19 @@
 name: SAST Scanning on PR
 on: 
-  #run the weekly scan on midnight Saturday
-  #schedule: 
-  #    - cron:  '0 0 * * 6' 
-  #run when changes happens to main/master branch
-  # push:
-    #branches:
-    #  - main
-     # - master 
-  # runs when a pull_request event's activity type is opened, edited or reopened
+  #workflow will run whenever a pull request is opened, synchronized(new commit pushed),reopened,or edited  
   pull_request:
     types: [opened, synchronize, reopened, edited]
 
 jobs:
   build:
     runs-on: self-hosted
+    env:
+      github_event_before: ${{ github.event.before }}
+      github_sha: ${{ github.sha }}
+      github_base_ref: ${{ github.base_ref }}
+      github_pull_request: ${{ github.event.pull_request.head.ref }}
+      github_event: ${{ github.event_name }}
+
     steps:
       - name: Checkout Repository
         uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v2
@@ -26,7 +25,7 @@ jobs:
         run: |
           echo "CODE_SCANNING_FILE=${WORKFLOWDIR}/github_scan_result.json" >> $GITHUB_ENV
           echo "ARTIFACT_PATH=${WORKFLOWDIR}/semgrep_scan_result.json" >> $GITHUB_ENV
-          echo "ARTIFACT_NAME=SAST-${GITHUB_RUN_ID}-${GITHUB_SHA}" >> $GITHUB_ENV
+          echo "ARTIFACT_NAME=SAST-PR-${GITHUB_RUN_ID}-${GITHUB_SHA}" >> $GITHUB_ENV
 
           echo "ANALYSE_FILE=${WORKFLOWDIR}/analyse_current_results.txt" >> $GITHUB_ENV
           echo "SUM_FILE=${WORKFLOWDIR}/scan_summary.txt" >> $GITHUB_ENV
@@ -35,7 +34,7 @@ jobs:
           echo "GITLEAKS_ARTIFACTS=${WORKFLOWDIR}/secret-af.json" >> $GITHUB_ENV
           echo "LAST_ARTIFACT_ZIP=${WORKFLOWDIR}/last-scans-output.zip" >> $GITHUB_ENV
       
-      - name: check if semgrep installed
+      - name: check if Semgrep installed
         run: |
          if ! command -v semgrep &> /dev/null; then
            echo "semgrep is not installed, installing..."
@@ -45,43 +44,30 @@ jobs:
          fi
         continue-on-error: true
 
-      - name: Run full scan with Semgrep 
+      - name: Run Semgrep scan on the modified files in the Pull request event 
         run: |
-          if [ "${{ github.event_name }}" == "pull_request" ]; then
+          if [ $github_event == "pull_request" ]; then
             # Fetch the changes made in the pull request
-            git fetch origin ${{ github.event.before }}:${{ github.event.after }} --depth=1     
-            echo "github event before: ${{ github.event.before }}"
-            echo "github event after:${{ github.event.after }}"
-
-            latest_commit_sha=$(git rev-parse HEAD)
-            echo "github latest commit sha is : $latest_commit_sha"
-            #previous_commit_sha=$(git rev-parse HEAD^)
-            #echo "Previous Commit SHA: $previous_commit_sha"
-
+            git fetch origin $github_base_ref $github_pull_request --depth=1   
             # Use git diff to get the list of changed files
-            edited_files=$(git diff --name-only ${{ github.event.after }} ${{ github.event.before }})
-            #edited_files=$(git diff --name-only $current_commit_sha $previous_commit_sha)
-            echo $edited_files
-
-            # Run semgrep only if there are edited files
+            git config advice.objectNameWarning false
+            edited_files=$(git diff --name-only $github_event_before $github_sha)
+            echo "changed files list: $edited_files"
+            # Run semgrep only if there are edited files. If multiple edited files, append these files to semgrep command
             if [ -n "$edited_files" ]; then
-              # Create an array of --include options for each edited file
-              include_options=()
+              semgrep_command="semgrep  --config="p/default" "
               for file in $edited_files; do
-                include_options+=("--include $file")
+                semgrep_command+=" $file" 
+                echo "$file"
               done
-  
-              # Run semgrep with the created include options
-              semgrep  "${include_options[@]}" --config="p/default" --json --output $ARTIFACT_PATH
+              eval "$semgrep_command --json --output $ARTIFACT_PATH"    
             else
               echo "No files edited in the latest commit. Semgrep scan skipped."
             fi
-          else
-            echo "Semgrep scan is skipped for non-push events."
           fi
         continue-on-error: true
       
-      - name: Processing SAST result (Please set the reporting severity level in GitHub Action Variables settings)
+      - name: Processing scan result (Please set the reporting severity level in GitHub Action Variables settings)
         run : |
           if [ -n "${{ vars.ISSUE_SEVERITY  }}" ]; then
             empty_issue_list=$(jq '.results[] | select(.extra.metadata.impact | IN(${{ vars.ISSUE_SEVERITY }})) ' $ARTIFACT_PATH | wc -l)
@@ -91,6 +77,8 @@ jobs:
               jq_filter='.results[] | select(.extra.metadata.impact | IN(${{ vars.ISSUE_SEVERITY }})) |  "- RuleID \(.extra.metadata."semgrep.dev".rule.rule_id) has detected a potential \(.extra.metadata.impact) impact \(.extra.metadata.vulnerability_class[0]) vulnerability in the \(.path) file (start from line \(.start.line)). "'
               jq -r "$jq_filter" "$ARTIFACT_PATH" > $ANALYSE_FILE 
               cat $ANALYSE_FILE    
+              # Exit with an error code to mark the check as failed
+              exit 1 
             else 
               echo "There are no issues with severity levels - "${{ vars.ISSUE_SEVERITY  }}", found in this scan. "
             fi 
@@ -103,6 +91,8 @@ jobs:
               jq_filter='.results[] | select(.extra.metadata.impact | IN("HIGH", "CRITICAL")) |  "- RuleID \(.extra.metadata."semgrep.dev".rule.rule_id) has detected a potential \(.extra.metadata.impact) impact \(.extra.metadata.vulnerability_class[0]) vulnerability in the \(.path) file (start from line \(.start.line)). "'
               jq -r "$jq_filter" "$ARTIFACT_PATH" > $ANALYSE_FILE  
               cat $ANALYSE_FILE 
+              # Exit with an error code to mark the check as failed
+              exit 1 
             else 
               echo "There are no issues with severity levels 'HIGH' or 'CRITICAL' found in this scan. "
             fi
@@ -112,57 +102,6 @@ jobs:
           echo "- Number of vulnerabilities detected in this scan: $(jq '.results| length' $ARTIFACT_PATH)  " >> $SUM_FILE
         continue-on-error: true
 
-      - name: Compare Current vs Previous SAST scan result 
-        if: ${{ env.leaks != 0 }} && 
-        run: |
-          bash -s << 'EOF'
-
-          # retrieve all artifacts from all GitHub Actions workflows
-          curl -L -o $PREV_ARTIFACTS \
-          -H "Accept: application/vnd.github+json" \
-          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
-          -H "X-GitHub-Api-Version: 2022-11-28" \
-          https://api.github.com/repos/${{ github.repository }}/actions/artifacts
-          
-          # filter artifacts from SAST workflows only. Then find the most recent artifact for SAST scanning
-          jq '[ .artifacts[] | select(.name | startswith("FMGL-SAST"))]' $PREV_ARTIFACTS > $GITLEAKS_ARTIFACTS
-          echo "list of all SAST-scanning artifacts"
-          cat $GITLEAKS_ARTIFACTS
-          LAST_A=$(jq '.[].created_at' $GITLEAKS_ARTIFACTS | sort -rV | head -n 1)
-          if [ -z $LAST_A ] ; then exit 0 ; fi
-
-          # if recent artifact is found, obtaining the Download URL for the most Recent Artifact
-          echo "Most recent scan with artifact is $LAST_A"
-          A_URL=$(jq '.artifacts[] | select(.created_at == '${LAST_A}') | .archive_download_url' $PREV_ARTIFACTS | tr -d '"')
-          if [ -z $A_URL ] ; then exit 0 ; fi
-          echo "fetching previous scan results:" $LAST_A $A_URL
-          curl -L -o $LAST_ARTIFACT_ZIP \
-          -H "Accept: application/vnd.github+json" \
-          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
-          -H "X-GitHub-Api-Version: 2022-11-28" $A_URL
-          
-          # if the ZIP file exists, extracts the contents of the ZIP file into that temp directory
-          if [ -e "$LAST_ARTIFACT_ZIP" ]; then
-            PREV_FILENAME=${WORKFLOWDIR}/previous_result.json
-            unzip -p $LAST_ARTIFACT_ZIP > $PREV_FILENAME
-            ls -lah $PREV_FILENAME
-
-            # format findings from previous result ($PREV_FILENAME) and current result ($ARTIFACT_PATH). These findings are sorted and unique results are saved.
-            format_findings(){ jq --compact-output '.[] | [.File , .Secret]' "$1"; }           
-            format_findings $PREV_FILENAME | sort | uniq > $WORKFLOWDIR/results-prev
-            format_findings $ARTIFACT_PATH | sort | uniq > $WORKFLOWDIR/results-current
-  
-            # compare the results from the previous run with the current run
-            diff_results=$(diff -u "$WORKFLOWDIR/results-prev" "$WORKFLOWDIR/results-current")
-            new_vulnerabilities=$(echo "$diff_results" | grep '^+\[' | wc -l)
-            echo "- Number of new vulnerabilities in this scan: $new_vulnerabilities" >> $SUM_FILE
-          else
-            echo "This repository has not been scanned previosly."  
-            echo "new_vulnerabilities=$new_vulnerabilities" >> $GITHUB_ENV   
-          fi
-          EOF
-        continue-on-error: true 
-      
       - name: Clean up
         run: |
           rm -rf $WORKFLOWDIR
